services:
    php:
        container_name: autosmozi-app
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - database
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]

    database:
        container_name: autosmozi-db
        image: mariadb:latest
        environment:
            - MARIADB_ROOT_PASSWORD=root_password
            - MARIADB_DATABASE=autosmozi
            - MARIADB_USER=autosmozi
            - MARIADB_PASSWORD=rwqPQkhqWXnbv3P
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        

volumes:
    mariadb_data:
 